language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install iron-icon#v1.0.9
- bower install
- polylint
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: kbJfoW5S0QpxsOYJxPbvYMNk0QLf63jDD7LSS0tfgrfWke9fgQ/egHSwd/LkOZwiZnIotBJhAmwC/khVBNTzwR1hh3pHZP/ZHnNR9tl8VglMvUfa0SjuV+04nD78+aGWV/Nbf1VCV+duW6Ur0c6h8SHMXaikfxLdKZM9WSHopVNkK0A9bLJAa2bD7LxC5f964XDQIgE+npELc7FuAHumX3hsgWxso528a3ZdNf9xsRbm70yac/GDkGKZPwy76vH/jMPp/3ITxYHHmzeRiELtVOtbmyD00MbL4+aDUe7E6NzJmzDr7ZuhlIWyAGp7lFiMsIlC2Dx2eNx852jqPfb3Vg41sQK0Vth6BhAoTi/vKmj14QM4WO8si2MncuLGT/lhjyQlaA7QbfG+38ykhnwb0/gYo9xIfA25RAIdcVnS1fZmYJREobfvtLNhCwJlo1LHDaa09Vxj6UY16cJWvHtlT3/C6HTCbf+qiAPvIdBaTdYGIMjce9GQnYqHmmpIUNqFh+8+I9v+wJroQVCVmFelxA2Ac1gF9Pd6Q0DVn5QtFg5NS3SIwhN//fWDh4N9+fofbZsizKQbLTSH3hyOX7Vvk4HsL1ZX7ZYrWyawGGUND5o30GEUaOnB/9qdum7I3YBxiiZWJ/GwQ5bv0NphrxiHnNVbD4EIgjJYlTV5ZXPXw88=
  - secure: QHp/20JnHnc9TAGYLCvf8MI95tMFHzFiy3f8RJqzmgSBdrPsmGVN8RCD9DmpGvqqqvuesX5vKTcIGZYqhhRpn+8ajHV+zXNwY78RUzVs3Grbx8O+DKbKtp/lQYfBfIyHv5E+ytQUCx+PCpQiUhEY2yZUMUtXhsZpTwRe+JRi2uozoK99962VPzWywI15E+2Rt9JShDZNHNDhNliXLZjWcvTr72ScHXKJW/dsbUE90HwNjynFyLWdv6n1zNs4LnNtollTsvBR9yEtoMTk6X44UsN6PQoE8JzbspGJ93FOVszXyW+RzizSC/ZhaQk6yKxJtVcAGPrLO+5+rNQsCAn4ho45MFM4JsuvWFnpJJV20epUEDMXFwhQKZdbOggBpiFF2la2i7qAPvDjGv0I/OsAW5+9ifIdZh5y9wnhrA+DnMahk+q68z18UZnhcz+NKgXLHIb3VHniLEAr8l5mpLRSUYd0kYGxms604eZfgxV87SvZcJS0d52k5MLk+jkmIG/kSD54d9l4eJ8PbQZyC7fc8G9cUEAGBKKwF4r517Z4QeElLB7ouZWjCyjPwoU2XQDD+Y3JjT4GgX6l85ZJhUJESKQd5u1uieX47BEA7Q7phDBoq+T38CNrZZMfbH8YaaYn7N53bZ/ZZFHfQqfBvR7QN6lQt5GXWN01KiNDi50Tr+4=
